version: '2.4'
services:
  mongo:
    image: mongo:latest

  go-api:
    build: ./app
    command: [ "go", "run", "." ]
    volumes:
      - ./app:/projects/app
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
